//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceListLoader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.9.9")]
        public string MisDbAddress {
            get {
                return ((string)(this["MisDbAddress"]));
            }
            set {
                this["MisDbAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("central")]
        public string MisDbName {
            get {
                return ((string)(this["MisDbName"]));
            }
            set {
                this["MisDbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sysdba")]
        public string MisDbUser {
            get {
                return ((string)(this["MisDbUser"]));
            }
            set {
                this["MisDbUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("masterkey")]
        public string MisDbPassword {
            get {
                return ((string)(this["MisDbPassword"]));
            }
            set {
                this["MisDbPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select first 1 S.SPRICE
    from WSCHEMA W
        join PRICESCONTRACTOR P on p.filial = @filid
                                and p.fdate <= current_date
        join SCHPRICECONTRACTOR S   on w.schid = s.schid
                                    and s.prid = p.prid
                                    and s.kateg = 14 --13-individual --14-legal-entity
    where
        w.schid = (
select schid 
from wschema 
where kodoper=@kodoper
and schname=@schname
and w.structid = 3)
        and w.structid = 3
        and (W.DISDATE is null or W.DISDATE > '01.01.2017')
        and (W.INVISINPRICE is null or W.INVISINPRICE = 0)
        and s.schid is not null
        and s.pricetype = 0
    order by w.schid, p.fdate desc")]
        public string MisDbSelectPriceByCode {
            get {
                return ((string)(this["MisDbSelectPriceByCode"]));
            }
            set {
                this["MisDbSelectPriceByCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("donotreply")]
        public string MailUser {
            get {
                return ((string)(this["MailUser"]));
            }
            set {
                this["MailUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("klNhr1hi9qp55weewAXd")]
        public string MailPassword {
            get {
                return ((string)(this["MailPassword"]));
            }
            set {
                this["MailPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bzklinika.ru")]
        public string MailDomain {
            get {
                return ((string)(this["MailDomain"]));
            }
            set {
                this["MailDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.bzklinika.ru")]
        public string MailSmtpServer {
            get {
                return ((string)(this["MailSmtpServer"]));
            }
            set {
                this["MailSmtpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nn-admin@bzklinika.ru")]
        public string MailCopy {
            get {
                return ((string)(this["MailCopy"]));
            }
            set {
                this["MailCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s.a.starodymov@bzklinika.ru")]
        public string MailTo {
            get {
                return ((string)(this["MailTo"]));
            }
            set {
                this["MailTo"] = value;
            }
        }
    }
}
